apiVersion: v1
kind: Service
metadata:
  name: "springboot-gitops" 
spec:
  #type: NodePort
  ports:
  # the port that this service should serve on
  - name: http
    port: 8080
  selector:
    app: "aspringboot-gitops"
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: "springboot-gitops"
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: "springboot-gitops"
    spec:
     containers:
      - name: springboot-gitops
        image: nykraj/gitops-poc:v1
        resources:
          requests:
            memory: "700Mi"
            cpu: "47m"
          limits:
            memory: "1024Mi"
            cpu: "500m"
      # - name: curl
      #   image: tutum/curl
      #   command: ["/bin/bash", "-c"]
      #   args: ["sleep infinity"]
